### ISSUE TITLE
Support for KSP 1.4

### ISSUE THREAD

**Issue by vinaychandra** [linuxgurugamer/FShangarExtender#2]
Please add support for KSP 1.4 Making History

**Comment by linuxgurugamer** [comment]
Please stop bugging me about updates

**Comment by linuxgurugamer** [comment]
See this thread
https://forum.kerbalspaceprogram.com/index.php?/topic/172193-help-me-prioritize-130-mod-updates/

Read the OP, and then post what you post.  Remember, contributions are appreciated and can move specific mods up my list
