### ISSUE TITLE
Fix Rescaling of Editor VAB

### ISSUE THREAD

**Issue by Sigma88** [linuxgurugamer/FShangarExtender#4]
I was asked by @StoneBlue to look into an issue with the rescale of the VAB

<img src="https://cdn.discordapp.com/attachments/381456455783415808/670044633908248606/unknown.png" width="50%" />

you can use this code to get the GameObject that contains those things and just change the scale (transform.localScale *= size multiplier)

```
GameObject building;
if (EditorDriver.editorFacility == EditorFacility.SPH)
    building = GameObject.Find("SPHlvl1") ?? GameObject.Find("SPHlvl2") ?? GameObject.Find("SPHmodern");
else
    building = GameObject.Find("VABlvl2") ?? GameObject.Find("VABlvl3") ?? GameObject.Find("VABmodern");
```

The object that you will find this way also contains the vehicles and the kerbals and boxes, so you might not want to rescale those 

if you want I can look into this further to find which are exactly the gameobjects you need to target

here is a video where I resize that part by a multiplier of 1.5 for 5 or 6 times in a row:

[video](https://cdn.discordapp.com/attachments/235584224650985472/670046684230713363/scale.mp4)

**Comment by Sigma88** [comment]
also, if you plan to include this, I might want to look into your code to make it compatible with [Sigma&nbsp;EditorView](https://github.com/Sigma88/Sigma-EditorView/)

**Comment by linuxgurugamer** [comment]
Hmmm.  Well, in as much as I'm just maintaining it, and don't really do much with the models, if you want to investigate further, go for it.

Otherwise, I probably won't get to it for a while, busy with some other stuff, and this isn't a "bug" so much as a  "feature"

**Comment by Sigma88** [comment]
Tbh I can't even reproduce the behaviour stoneblue reported so I have no idea what is going on there

When I have some time I'll take a look and send you a PR

**Comment by linuxgurugamer** [comment]
What he is referring to is that when you hit the * to activate the mod, the entire VAB/SPH just disappears and the building is done on the grassy plains.  I'll see if I can get you a video this evening

**Comment by Sigma88** [comment]
Yes that's the behaviour I see, the building just disappears.

However in the screenshots the building is actually visible and rescaled to a bigger size, with also a piece of the building that failed to resize and remained in the original position

**Comment by linuxgurugamer** [comment]
That may depend on the level the building has been researched to.

**Comment by Sigma88** [comment]
I should have some time to look into it tonight, I'll let you know if I find anything
